---
- name: Download RHCOS files to matchbox
  get_url:
    url: "{{ rhcos_base_url }}/{{ item }}"
    dest: /var/lib/matchbox/assets/
  loop:
  - "{{ rhcos_kernel }}"
  - "{{ rhcos_initramfs }}"
  - "{{ rhcos_metal }}"
  when: rhcos_download == true

- name: Copy RHCOS files to matchbox
  copy:
    src: "{{ item }}"
    dest: /var/lib/matchbox/assets/
    owner: matchbox
    group: matchbox
  loop:
  - "{{ rhcos_kernel }}"
  - "{{ rhcos_initramfs }}"
  - "{{ rhcos_metal }}"
  when: rhcos_download == false  
